### ISSUE TITLE
GoooQo Roadmap before Version 1.0

### ISSUE THREAD

**Issue by f0rb** [doytowin/goooqo#3]
### v0.1.x
- [x] Field Mappging features
  - [x] Query Object Mapping
    - [x] Overall
    - [x] Page
    - [x] Sort
  - [x] Field Mapping
    - [x] Custom Condition Mapping
    - [x] Basic Suffix Mapping
      - [x] Ne
      - [x] Not
      - [x] Eq
      - [x] Lt
      - [x] Le
      - [x] Gt
      - [x] Ge
      - [x] Lt
      - [x] Null
      - [x] In
      - [x] NotIn
      - [x] Like
      - [x] Contain
      - [x] Start
      - [x] End
      - [x] NotLike
      - [x] NotContain
      - [x] NotStart
      - [x] NotEnd
      - [x] Rx
    - [x] Or Suffix Mapping
      - [x] struct type
      - [x] basic type array
      - [x] struct type array
- [x] Statement Building
  - [x] SELECT by id
  - [x] SELECT by Query
  - [x] UPDATE
  - [x] UPDATE partial
  - [x] PATCH by Query
  - [x] DELETE by id
  - [x] DELETE by Query
  - [x] CREATE
  - [X] CREATE Multi
- [X] DataAccess(Core)
  - [x] Get(ID)
  - [x] Query(Q)
  - [x] Count(Q)
  - [x] Page(Q)
  - [x] Create(E)
  - [X] CreateMulti(E[])
  - [x] Update(E)
  - [x] PatchOne(E)
  - [X] Patch(E Q)
  - [x] DeleteById(ID)
  - [x] Delete(Q)
- [x] Field Type (Language Based)
  - [x] int
  - [x] bool
  - [x] string
  - [x] array
  - [x] time
- Web Module
  - [x] RESTFul APIs
    - [x] Get /id
    - [x] Page /
    - [x] Post /
    - [X] Put /id
    - [X] Patch /id
    - [x] PatchByQuery /
    - [X] Delete /id
    - [x] DeleteByQuery /
-  Transaction Module
  - [x] StartTransaction
  - [x] Commit
  - [x] Rollback
  - [x] SavePoint/RollbackTo

### v0.2.x
- [ ] Field Mapping
  - [ ] Subquery
    - [ ] ALL
    - [ ] ANY
  - [ ] DomainPath
    - [ ] one-to-one
    - [ ] many-to-one
    - [ ] one-to-many
    - [ ] many-to-many
- [ ] Associative Service
  - [ ] Create
  - [ ] Delete
  - [ ] Query
- [ ] Aggregate Service
  - [ ] query
  - [ ] count
    
### v0.3.x
- [ ] Aggregation
  - [ ] Custom Expression
  - [ ] Aggregate Prefix
    - [ ] Sum
    - [ ] Max
    - [ ] Min
    - [ ] Avg
    - [ ] First
    - [ ] Last
    - [ ] StdDevPop("stddev_pop")
    - [ ] StdDevSamp("stddev_samp")
    - [ ] StdDev("stddev")
    - [ ] AddToSet
    - [ ] Push
    - [ ] Count
  - [ ] Group By
  - [ ] Having
  - [ ] Natural Join
  - [ ] Outer Join
- [ ] TPC-H
  - [ ] Q01
  - [ ] Q02
  - [ ] Q03
  - [ ] Q04
  - [ ] Q05
  - [ ] Q06
  - [ ] Q07
  - [ ] Q08
  - [ ] Q09
  - [ ] Q10
  - [ ] Q11
  - [ ] Q12
  - [ ] Q13
  - [ ] Q14
  - [ ] Q15
  - [ ] Q16
  - [ ] Q17
  - [ ] Q18
  - [ ] Q19
  - [ ] Q20
  - [ ] Q21
  - [ ] Q22

### v0.4.x
- [ ] Dialect
  - [ ] MySQL8
  - [ ] Oracle
  - [ ] SQL Server
  - [ ] PostgreSQL
